### ISSUE TITLE
Creating Card

### ISSUE THREAD

**Issue by amiresmaeili79** [Anatidaephobia-SE/swan-server#82]
There is a tiny bug in creating a new card for idea section.  
* User should be able to create a card without any **tag**.
* User should be able to create a card without any **assignee**

**Comment by zhsn99** [comment]
> There is a tiny bug in creating a new card for idea section.
> 
> * User should be able to create a card without any **tag**.
> * User should be able to create a card without any **assignee**

Hi.
Yes, you are right. Thank you for writing this issue. I've pushed changes #89; please check it out, and if there were still problems, just let me know.
